#!/usr/bin/env bash
#
# (c) 2014 RDashINC

export os_name=$(expr substr $(uname -s) 1 6)

if [ "$1" == "--force-linux" ]; then
	export os_name=""
fi

if [ "$os_name" == "CYGWIN" ]; then
	echo "Using Cygwin, windows operating system."
	export os="win32"
	pushd "../" >/dev/null
	export basedir=$(get_basedir.cmd)
	popd >/dev/null
else
	echo "Using a linux flavor or etc."
	export os="Linux"
	export basedir=$(source get_basedir)
fi


export username=rainbowdashdc

source mod/mod_cecho.bash
source mod/mod_aload.bash
source mod/mod_extcolors.bash
source mod/mod_ui.bash
draw_main && prompt
