#!/bin/bash

## Here's an example story, each level is designed by LEVELNUMBER_SUBSECTION
## This is just how the engine handles progressing between levels.

function 1_1 {
	description "A figure emerges from the darkness, facing towards you"

	send_output "Hello, $username..."
	send_output "It's nice to finally meet you."

	prompt


	# wait for a yes
	send_output "Are you ready to begin your journey?"
	prompt
	local choice=$(get_input)
	until [[ "$choice" == "yes" ]]; do
		player_thinks "You get the feeling that's not the right answer."
		prompt
		choice=$(get_input)
	done

	send_output "Very good, let us begin ..."
	prompt
}
